// Copyright Valkey GLIDE Project Contributors - SPDX Identifier: Apache-2.0

namespace Valkey.Glide.Commands;

/// <summary>
/// Stream commands for clients.
/// </summary>
/// <seealso href="https://valkey.io/commands/#stream">Valkey – Stream Commands</seealso>
public interface IStreamBaseCommands
{
    /// <summary>
    /// Appends a new entry to a stream with a single field-value pair.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xadd"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="streamField">The field name.</param>
    /// <param name="streamValue">The field value.</param>
    /// <param name="messageId">The message ID. Use null or <see cref="StreamConstants.AutoGeneratedId"/>  for auto-generation, or "&lt;ms&gt;-*" to auto-generate sequence number for a specific timestamp.</param>
    /// <param name="maxLength">The maximum length of the stream. If specified, old entries will be trimmed.</param>
    /// <param name="useApproximateMaxLength">If true, uses approximate trimming (~) for better performance.</param>
    /// <returns>The ID of the added entry.</returns>
    Task<ValkeyValue> StreamAddAsync(ValkeyKey key, ValkeyValue streamField, ValkeyValue streamValue, ValkeyValue? messageId, int? maxLength, bool useApproximateMaxLength);

    /// <summary>
    /// Appends a new entry to a stream with multiple field-value pairs.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xadd"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="streamPairs">The field-value pairs to add.</param>
    /// <param name="messageId">The message ID. Use null or <see cref="StreamConstants.AutoGeneratedId"/>  for auto-generation, or "&lt;ms&gt;-*" to auto-generate sequence number for a specific timestamp.</param>
    /// <param name="maxLength">The maximum length of the stream. If specified, old entries will be trimmed.</param>
    /// <param name="useApproximateMaxLength">If true, uses approximate trimming (~) for better performance.</param>
    /// <returns>The ID of the added entry.</returns>
    Task<ValkeyValue> StreamAddAsync(
        ValkeyKey key,
        IEnumerable<NameValueEntry> streamPairs,
        ValkeyValue? messageId,
        int? maxLength,
        bool useApproximateMaxLength);

    /// <summary>
    /// Appends a new entry to a stream with a single field-value pair.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xadd"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="streamField">The field name.</param>
    /// <param name="streamValue">The field value.</param>
    /// <param name="messageId">The message ID. Use null or <see cref="StreamConstants.AutoGeneratedId"/>  for auto-generation, or "&lt;ms&gt;-*" to auto-generate sequence number for a specific timestamp.</param>
    /// <param name="maxLength">The maximum length of the stream. If specified, old entries will be trimmed.</param>
    /// <param name="useApproximateMaxLength">If true, uses approximate trimming (~) for better performance.</param>
    /// <param name="limit">The maximum number of entries to trim. Only applicable when useApproximateMaxLength is true.</param>
    /// <param name="noMakeStream">If true, the stream will not be created if it doesn't exist. Returns null if stream doesn't exist.</param>
    /// <returns>The ID of the added entry, or null if noMakeStream is true and the stream doesn't exist.</returns>
    Task<ValkeyValue> StreamAddAsync(ValkeyKey key, ValkeyValue streamField, ValkeyValue streamValue, ValkeyValue? messageId = null, long? maxLength = null, bool useApproximateMaxLength = false, long? limit = null, bool noMakeStream = false);

    /// <summary>
    /// Appends a new entry to a stream with multiple field-value pairs.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xadd"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="streamPairs">The field-value pairs to add.</param>
    /// <param name="messageId">The message ID. Use null or <see cref="StreamConstants.AutoGeneratedId"/>  for auto-generation, or "&lt;ms&gt;-*" to auto-generate sequence number for a specific timestamp.</param>
    /// <param name="maxLength">The maximum length of the stream. If specified, old entries will be trimmed.</param>
    /// <param name="useApproximateMaxLength">If true, uses approximate trimming (~) for better performance.</param>
    /// <param name="limit">The maximum number of entries to trim. Only applicable when useApproximateMaxLength is true.</param>
    /// <param name="noMakeStream">If true, the stream will not be created if it doesn't exist. Returns null if stream doesn't exist.</param>
    /// <returns>The ID of the added entry, or null if noMakeStream is true and the stream doesn't exist.</returns>
    Task<ValkeyValue> StreamAddAsync(
        ValkeyKey key,
        IEnumerable<NameValueEntry> streamPairs,
        ValkeyValue? messageId = null,
        long? maxLength = null,
        bool useApproximateMaxLength = false,
        long? limit = null,
        bool noMakeStream = false);

    /// <summary>
    /// Reads entries from a single stream starting from a given position.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xread"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="position">The position from which to start reading. Use <see cref="StreamPosition.Beginning"/> to read from the beginning.</param>
    /// <param name="countPerStream">The maximum number of entries to return.</param>
    /// <returns>An array of stream entries, or an empty array if no entries are available.</returns>
    Task<StreamEntry[]> StreamReadAsync(ValkeyKey key, ValkeyValue position, int? countPerStream = null);

    /// <summary>
    /// Reads entries from multiple streams starting from given positions.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xread"/>
    /// <param name="streamPositions">A collection of stream keys and their starting positions.</param>
    /// <param name="countPerStream">The maximum number of entries to return per stream.</param>
    /// <returns>An array of streams with their entries, or an empty array if no entries are available.</returns>
    Task<ValkeyStream[]> StreamReadAsync(IEnumerable<StreamPosition> streamPositions, int? countPerStream = null);

    /// <summary>
    /// Returns the entries in a stream within a specified range of IDs.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xrange"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="start">The ID for the start of the range (inclusive). Use <see cref="StreamConstants.ReadMinValue"/>  for the smallest ID in the stream.</param>
    /// <param name="end">The ID for the end of the range (inclusive). Use <see cref="StreamConstants.ReadMaxValue"/>  for the largest ID in the stream.</param>
    /// <param name="count">The maximum number of entries to return.</param>
    /// <param name="order">The order to return entries (Ascending uses XRANGE, Descending uses XREVRANGE).</param>
    /// <returns>An array of stream entries in the specified range.</returns>
    Task<StreamEntry[]> StreamRangeAsync(ValkeyKey key, ValkeyValue? start = null, ValkeyValue? end = null, int? count = null, Order order = Order.Ascending);

    /// <summary>
    /// Creates a consumer group for a stream.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xgroup-create"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="position">The position from which to start reading. Use <see cref="StreamConstants.NewMessages"/>  for new messages, <see cref="StreamConstants.AllMessages"/>  for all messages. Defaults to <see cref="StreamConstants.NewMessages"/>  if null.</param>
    /// <returns>A task that completes when the consumer group has been created. Throws on failure.</returns>
    // TODO #263: Move to IClient.StreamCommands; signature diverges from SER (Task vs Task<bool>).
    Task StreamCreateConsumerGroupAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue? position);

    /// <summary>
    /// Creates a consumer group for a stream.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xgroup-create"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="position">The position from which to start reading. Use <see cref="StreamConstants.NewMessages"/>  for new messages, <see cref="StreamConstants.AllMessages"/>  for all messages. Defaults to <see cref="StreamConstants.NewMessages"/>  if null.</param>
    /// <param name="createStream">If true, creates the stream if it doesn't exist.</param>
    /// <param name="entriesRead">Valkey 7.0+: Sets the entries_read counter to an arbitrary value.</param>
    /// <returns>A task that completes when the consumer group has been created. Throws on failure.</returns>
    // TODO #263: Move to IClient.StreamCommands; signature diverges from SER (Task vs Task<bool>).
    Task StreamCreateConsumerGroupAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue? position = null, bool createStream = true, long? entriesRead = null);

    /// <summary>
    /// Destroys a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xgroup-destroy"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <returns>True if the group was destroyed, false otherwise.</returns>
    Task<bool> StreamDeleteConsumerGroupAsync(ValkeyKey key, ValkeyValue groupName);

    /// <summary>
    /// Creates a consumer in a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xgroup-createconsumer"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="consumerName">The consumer name to create.</param>
    /// <returns>True if the consumer was created, false if it already existed.</returns>
    Task<bool> StreamCreateConsumerAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue consumerName);

    /// <summary>
    /// Deletes a consumer from a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xgroup-delconsumer"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="consumerName">The consumer name.</param>
    /// <returns>The number of pending messages the consumer had before deletion.</returns>
    Task<long> StreamDeleteConsumerAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue consumerName);

    /// <summary>
    /// Sets the position from which to read a stream for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xgroup-setid"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="position">The position from which to read.</param>
    /// <param name="entriesRead">Valkey 7.0+: Sets the entries_read counter to an arbitrary value.</param>
    /// <returns>A task that completes when the position has been set. Throws on failure.</returns>
    // TODO #263: Move to IClient.StreamCommands; signature diverges from SER (Task vs Task<bool>).
    Task StreamConsumerGroupSetPositionAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue position, long? entriesRead = null);

    /// <summary>
    /// Reads entries from a stream for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xreadgroup"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="consumerName">The consumer name.</param>
    /// <param name="position">The position from which to read. Use <see cref="StreamConstants.UndeliveredMessages"/>  for new messages only. Defaults to <see cref="StreamConstants.UndeliveredMessages"/>  if null.</param>
    /// <param name="count">The maximum number of entries to return.</param>
    /// <returns>An array of stream entries.</returns>
    Task<StreamEntry[]> StreamReadGroupAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue consumerName, ValkeyValue? position, int? count);

    /// <summary>
    /// Reads entries from a stream for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xreadgroup"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="consumerName">The consumer name.</param>
    /// <param name="position">The position from which to read. Use <see cref="StreamConstants.UndeliveredMessages"/>  for new messages only. Defaults to <see cref="StreamConstants.UndeliveredMessages"/>  if null.</param>
    /// <param name="count">The maximum number of entries to return.</param>
    /// <param name="noAck">If true, messages are not added to the pending entries list.</param>
    /// <returns>An array of stream entries.</returns>
    Task<StreamEntry[]> StreamReadGroupAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue consumerName, ValkeyValue? position = null, int? count = null, bool noAck = false);

    /// <summary>
    /// Reads entries from multiple streams for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xreadgroup"/>
    /// <param name="streamPositions">A collection of stream keys and their starting positions.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="consumerName">The consumer name.</param>
    /// <param name="countPerStream">The maximum number of entries to return per stream.</param>
    /// <returns>An array of streams with their entries.</returns>
    Task<ValkeyStream[]> StreamReadGroupAsync(IEnumerable<StreamPosition> streamPositions, ValkeyValue groupName, ValkeyValue consumerName, int? countPerStream);

    /// <summary>
    /// Reads entries from multiple streams for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xreadgroup"/>
    /// <param name="streamPositions">A collection of stream keys and their starting positions.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="consumerName">The consumer name.</param>
    /// <param name="countPerStream">The maximum number of entries to return per stream.</param>
    /// <param name="noAck">If true, messages are not added to the pending entries list.</param>
    /// <returns>An array of streams with their entries.</returns>
    Task<ValkeyStream[]> StreamReadGroupAsync(IEnumerable<StreamPosition> streamPositions, ValkeyValue groupName, ValkeyValue consumerName, int? countPerStream = null, bool noAck = false);

    /// <summary>
    /// Acknowledges a message in a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xack"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="messageId">The message ID to acknowledge.</param>
    /// <returns>The number of messages acknowledged.</returns>
    Task<long> StreamAcknowledgeAsync(ValkeyKey key, ValkeyValue groupName, ValkeyValue messageId);

    /// <summary>
    /// Acknowledges messages in a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xack"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="messageIds">A collection of message IDs to acknowledge.</param>
    /// <returns>The number of messages acknowledged.</returns>
    Task<long> StreamAcknowledgeAsync(ValkeyKey key, ValkeyValue groupName, IEnumerable<ValkeyValue> messageIds);

    /// <summary>
    /// Returns pending messages summary for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xpending"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <returns>Summary information about pending messages.</returns>
    Task<StreamPendingInfo> StreamPendingAsync(ValkeyKey key, ValkeyValue groupName);

    /// <summary>
    /// Returns detailed pending messages for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xpending"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="count">The maximum number of entries to return.</param>
    /// <param name="consumerName">Filter by consumer name.</param>
    /// <param name="minId">The minimum ID (inclusive). Defaults to <see cref="StreamConstants.ReadMinValue"/>  (smallest ID) if null.</param>
    /// <param name="maxId">The maximum ID (inclusive). Defaults to <see cref="StreamConstants.ReadMaxValue"/>  (largest ID) if null.</param>
    /// <returns>An array of detailed information about each pending message.</returns>
    Task<StreamPendingMessageInfo[]> StreamPendingMessagesAsync(ValkeyKey key, ValkeyValue groupName, int count, ValkeyValue consumerName, ValkeyValue? minId, ValkeyValue? maxId);

    /// <summary>
    /// Returns detailed pending messages for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xpending"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <param name="count">The maximum number of entries to return.</param>
    /// <param name="consumerName">Filter by consumer name.</param>
    /// <param name="minId">The minimum ID (inclusive). Defaults to <see cref="StreamConstants.ReadMinValue"/>  (smallest ID) if null.</param>
    /// <param name="maxId">The maximum ID (inclusive). Defaults to <see cref="StreamConstants.ReadMaxValue"/>  (largest ID) if null.</param>
    /// <param name="minIdleTimeInMs">The minimum idle time in milliseconds.</param>
    /// <returns>An array of detailed information about each pending message.</returns>
    Task<StreamPendingMessageInfo[]> StreamPendingMessagesAsync(ValkeyKey key, ValkeyValue groupName, int count, ValkeyValue consumerName, ValkeyValue? minId = null, ValkeyValue? maxId = null, long? minIdleTimeInMs = null);

    /// <summary>
    /// Claims pending messages for a consumer.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xclaim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="consumerGroup">The consumer group name.</param>
    /// <param name="claimingConsumer">The consumer claiming the messages.</param>
    /// <param name="minIdleTimeInMs">The minimum idle time in milliseconds.</param>
    /// <param name="messageIds">A collection of message IDs to claim.</param>
    /// <returns>An array of claimed stream entries.</returns>
    Task<StreamEntry[]> StreamClaimAsync(ValkeyKey key, ValkeyValue consumerGroup, ValkeyValue claimingConsumer, long minIdleTimeInMs, IEnumerable<ValkeyValue> messageIds);

    /// <summary>
    /// Claims pending messages for a consumer.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xclaim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="consumerGroup">The consumer group name.</param>
    /// <param name="claimingConsumer">The consumer claiming the messages.</param>
    /// <param name="minIdleTimeInMs">The minimum idle time in milliseconds.</param>
    /// <param name="messageIds">A collection of message IDs to claim.</param>
    /// <param name="idleTimeInMs">Set the idle time (last delivery time) of the message.</param>
    /// <param name="timeUnixMs">Set the idle time to a specific Unix time in milliseconds.</param>
    /// <param name="retryCount">Set the retry counter to the specified value.</param>
    /// <param name="force">Create PEL entry even if message not already assigned to a consumer.</param>
    /// <returns>An array of claimed stream entries.</returns>
    Task<StreamEntry[]> StreamClaimAsync(ValkeyKey key, ValkeyValue consumerGroup, ValkeyValue claimingConsumer, long minIdleTimeInMs, IEnumerable<ValkeyValue> messageIds, long? idleTimeInMs = null, long? timeUnixMs = null, int? retryCount = null, bool force = false);

    /// <summary>
    /// Claims pending messages for a consumer, returning only IDs.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xclaim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="consumerGroup">The consumer group name.</param>
    /// <param name="claimingConsumer">The consumer claiming the messages.</param>
    /// <param name="minIdleTimeInMs">The minimum idle time in milliseconds.</param>
    /// <param name="messageIds">A collection of message IDs to claim.</param>
    /// <returns>An array of claimed message IDs.</returns>
    Task<ValkeyValue[]> StreamClaimIdsOnlyAsync(ValkeyKey key, ValkeyValue consumerGroup, ValkeyValue claimingConsumer, long minIdleTimeInMs, IEnumerable<ValkeyValue> messageIds);

    /// <summary>
    /// Claims pending messages for a consumer, returning only IDs.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xclaim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="consumerGroup">The consumer group name.</param>
    /// <param name="claimingConsumer">The consumer claiming the messages.</param>
    /// <param name="minIdleTimeInMs">The minimum idle time in milliseconds.</param>
    /// <param name="messageIds">A collection of message IDs to claim.</param>
    /// <param name="idleTimeInMs">Set the idle time (last delivery time) of the message.</param>
    /// <param name="timeUnixMs">Set the idle time to a specific Unix time in milliseconds.</param>
    /// <param name="retryCount">Set the retry counter to the specified value.</param>
    /// <param name="force">Create PEL entry even if message not already assigned to a consumer.</param>
    /// <returns>An array of claimed message IDs.</returns>
    Task<ValkeyValue[]> StreamClaimIdsOnlyAsync(ValkeyKey key, ValkeyValue consumerGroup, ValkeyValue claimingConsumer, long minIdleTimeInMs, IEnumerable<ValkeyValue> messageIds, long? idleTimeInMs = null, long? timeUnixMs = null, int? retryCount = null, bool force = false);

    /// <summary>
    /// Automatically claims pending messages.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xautoclaim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="consumerGroup">The consumer group name.</param>
    /// <param name="claimingConsumer">The consumer claiming the messages.</param>
    /// <param name="minIdleTimeInMs">The minimum idle time in milliseconds.</param>
    /// <param name="startAtId">The starting ID to scan for pending messages.</param>
    /// <param name="count">The maximum number of entries to claim. Defaults to 100 if null.</param>
    /// <returns>Result containing next start ID, claimed entries, and deleted IDs.</returns>
    Task<StreamAutoClaimResult> StreamAutoClaimAsync(ValkeyKey key, ValkeyValue consumerGroup, ValkeyValue claimingConsumer, long minIdleTimeInMs, ValkeyValue startAtId, int? count = null);

    /// <summary>
    /// Automatically claims pending messages, returning only IDs.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xautoclaim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="consumerGroup">The consumer group name.</param>
    /// <param name="claimingConsumer">The consumer claiming the messages.</param>
    /// <param name="minIdleTimeInMs">The minimum idle time in milliseconds.</param>
    /// <param name="startAtId">The starting ID to scan for pending messages.</param>
    /// <param name="count">The maximum number of entries to claim. Defaults to 100 if null.</param>
    /// <returns>Result containing next start ID, claimed IDs, and deleted IDs.</returns>
    Task<StreamAutoClaimIdsOnlyResult> StreamAutoClaimIdsOnlyAsync(ValkeyKey key, ValkeyValue consumerGroup, ValkeyValue claimingConsumer, long minIdleTimeInMs, ValkeyValue startAtId, int? count = null);

    /// <summary>
    /// Returns the number of entries in a stream.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xlen"/>
    /// <param name="key">The key of the stream.</param>
    /// <returns>The number of entries in the stream.</returns>
    Task<long> StreamLengthAsync(ValkeyKey key);

    /// <summary>
    /// Removes one or more messages from a stream.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xdel"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="messageIds">A collection of message IDs to delete.</param>
    /// <returns>The number of messages deleted.</returns>
    Task<long> StreamDeleteAsync(ValkeyKey key, IEnumerable<ValkeyValue> messageIds);

    /// <summary>
    /// Trims the stream to a specified size.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xtrim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="maxLength">The maximum length of the stream.</param>
    /// <param name="useApproximateMaxLength">If true, uses approximate trimming (~) for better performance.</param>
    /// <returns>The number of entries deleted.</returns>
    Task<long> StreamTrimAsync(ValkeyKey key, int maxLength, bool useApproximateMaxLength);

    /// <summary>
    /// Trims the stream to a specified size.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xtrim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="maxLength">The maximum length of the stream.</param>
    /// <param name="useApproximateMaxLength">If true, uses approximate trimming (~) for better performance.</param>
    /// <param name="limit">The maximum number of entries to trim. Only applicable when useApproximateMaxLength is true.</param>
    /// <returns>The number of entries deleted.</returns>
    Task<long> StreamTrimAsync(ValkeyKey key, long? maxLength = null, bool useApproximateMaxLength = false, long? limit = null);

    /// <summary>
    /// Trims the stream by minimum ID.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xtrim"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="minId">Trim entries with IDs lower than this.</param>
    /// <param name="useApproximateMaxLength">If true, uses approximate trimming (~) for better performance.</param>
    /// <param name="limit">The maximum number of entries to trim.</param>
    /// <returns>The number of entries deleted.</returns>
    Task<long> StreamTrimByMinIdAsync(ValkeyKey key, ValkeyValue minId, bool useApproximateMaxLength = false, long? limit = null);

    /// <summary>
    /// Returns stream information.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xinfo-stream"/>
    /// <param name="key">The key of the stream.</param>
    /// <returns>Information about the stream.</returns>
    Task<StreamInfo> StreamInfoAsync(ValkeyKey key);

    /// <summary>
    /// Returns consumer group information for a stream.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xinfo-groups"/>
    /// <param name="key">The key of the stream.</param>
    /// <returns>An array of information about each consumer group.</returns>
    Task<StreamGroupInfo[]> StreamGroupInfoAsync(ValkeyKey key);

    /// <summary>
    /// Returns consumer information for a consumer group.
    /// </summary>
    /// <seealso href="https://valkey.io/commands/xinfo-consumers"/>
    /// <param name="key">The key of the stream.</param>
    /// <param name="groupName">The consumer group name.</param>
    /// <returns>An array of information about each consumer in the group.</returns>
    Task<StreamConsumerInfo[]> StreamConsumerInfoAsync(ValkeyKey key, ValkeyValue groupName);

    // Obsolete methods - not supported by Valkey GLIDE

    /// <summary>
    /// This method is not implemented. Valkey does not support acknowledging and deleting messages in a single operation.
    /// </summary>
    [Obsolete("This method is not implemented. Use StreamAcknowledgeAsync followed by StreamDeleteAsync instead.", error: true)]
    Task<long> StreamAcknowledgeAndDeleteAsync(ValkeyKey key, ValkeyValue groupName, IEnumerable<ValkeyValue> messageIds);

    /// <summary>
    /// This method is not implemented. The mode parameter is not supported by Valkey GLIDE.
    /// </summary>
    [Obsolete("This method is not implemented. Use StreamDeleteAsync without the mode parameter instead.", error: true)]
    Task<long> StreamDeleteAsync(ValkeyKey key, IEnumerable<ValkeyValue> messageIds, object mode);

    /// <summary>
    /// This method is not implemented. The mode parameter is not supported by Valkey GLIDE.
    /// </summary>
    [Obsolete("This method is not implemented. Use StreamAddAsync without the mode parameter instead.", error: true)]
    Task<ValkeyValue> StreamAddAsync(ValkeyKey key, IEnumerable<NameValueEntry> streamPairs, ValkeyValue? messageId, long? maxLength, bool useApproximateMaxLength, long? limit, bool noMakeStream, ValkeyValue? minId, object mode);

    /// <summary>
    /// This method is not implemented. The mode parameter is not supported by Valkey GLIDE.
    /// </summary>
    [Obsolete("This method is not implemented. Use StreamTrimAsync without the mode parameter instead.", error: true)]
    Task<long> StreamTrimAsync(ValkeyKey key, long? maxLength, bool useApproximateMaxLength, long? limit, ValkeyValue? minId, object mode);

}
