using System;

namespace Valkey.Glide;

internal static class ValkeyLiterals
{
    // unlike primary commands, these do not get altered by the command-map; we may as
    // well compute the bytes once and share them
    public static readonly ValkeyValue
        @default = "default",
        ACLCAT = "ACLCAT",
        ADDR = "ADDR",
        ABSTTL = "ABSTTL",
        AFTER = "AFTER",
        AGGREGATE = "AGGREGATE",
        ALPHA = "ALPHA",
        ASYNC = "ASYNC",
        AND = "AND",
        ANY = "ANY",
        ASC = "ASC",
        AUTH = "AUTH",
        BEFORE = "BEFORE",
        BIT = "BIT",
        BLOCK = "BLOCK",
        BY = "BY",
        BYLEX = "BYLEX",
        BYSCORE = "BYSCORE",
        BYTE = "BYTE",
        CH = "CH",
        CHANNELS = "CHANNELS",
        CLUSTER = "CLUSTER",
        COPY = "COPY",
        COUNT = "COUNT",
        DB = "DB",
        DESC = "DESC",
        DOCTOR = "DOCTOR",
        ENCODING = "ENCODING",
        EX = "EX",
        EXAT = "EXAT",
        EXISTS = "EXISTS",
        FIELDS = "FIELDS",
        FILTERBY = "FILTERBY",
        FLUSH = "FLUSH",
        FNX = "FNX",
        FORCE = "FORCE",
        FREQ = "FREQ",
        FXX = "FXX",
        GET = "GET",
        GETKEYS = "GETKEYS",
        GETNAME = "GETNAME",
        GT = "GT",
        HISTORY = "HISTORY",
        ID = "ID",
        IDLE = "IDLE",
        IDLETIME = "IDLETIME",
        IDX = "IDX",
        IFEQ = "IFEQ",
        INCR = "INCR",
        KEEPTTL = "KEEPTTL",
        KILL = "KILL",
        LADDR = "LADDR",
        LATEST = "LATEST",
        LEFT = "LEFT",
        LEN = "LEN",
        lib_name = "lib-name",
        lib_ver = "lib-ver",
        LIMIT = "LIMIT",
        LIST = "LIST",
        LOAD = "LOAD",
        LT = "LT",
        MALLOC_STATS = "MALLOC-STATS",
        MATCH = "MATCH",
        MAX = "MAX",
        MAXAGE = "MAXAGE",
        MAXLEN = "MAXLEN",
        MIN = "MIN",
        MINID = "MINID",
        MINMATCHLEN = "MINMATCHLEN",
        MODULE = "MODULE",
        NOACK = "NOACK",
        NODES = "NODES",
        NOMKSTREAM = "NOMKSTREAM",
        NOSAVE = "NOSAVE",
        NOT = "NOT",
        NOVALUES = "NOVALUES",
        NUMPAT = "NUMPAT",
        NUMSUB = "NUMSUB",
        NX = "NX",
        OBJECT = "OBJECT",
        OR = "OR",
        PATTERN = "PATTERN",
        PAUSE = "PAUSE",
        PERSIST = "PERSIST",
        PING = "PING",
        PRIMARY = "PRIMARY",
        PURGE = "PURGE",
        PX = "PX",
        PXAT = "PXAT",
        RANK = "RANK",
        REFCOUNT = "REFCOUNT",
        REPLACE = "REPLACE",
        RESET = "RESET",
        RESETSTAT = "RESETSTAT",
        RETRYCOUNT = "RETRYCOUNT",
        REV = "REV",
        REWRITE = "REWRITE",
        RIGHT = "RIGHT",
        SAVE = "SAVE",
        SEGFAULT = "SEGFAULT",
        SET = "SET",
        SETINFO = "SETINFO",
        SETNAME = "SETNAME",
        SKIPME = "SKIPME",
        STATS = "STATS",
        STORE = "STORE",
        STREAMS = "STREAMS",
        SYNC = "SYNC",
        TIME = "TIME",
        TYPE = "TYPE",
        USERNAME = "USERNAME",
        VERSION = "VERSION",
        WEIGHTS = "WEIGHTS",
        WITHMATCHLEN = "WITHMATCHLEN",
        WITHSCORE = "WITHSCORE",
        WITHSCORES = "WITHSCORES",
        WITHVALUES = "WITHVALUES",
        XOR = "XOR",
        XX = "XX",

        // Sentinel Literals
        MASTERS = "MASTERS",
        MASTER = "MASTER",
        REPLICAS = "REPLICAS",
        SLAVES = "SLAVES",
        GETMASTERADDRBYNAME = "GET-MASTER-ADDR-BY-NAME",
        // RESET = "RESET",
        FAILOVER = "FAILOVER",
        SENTINELS = "SENTINELS",

        // Sentinel Literals as of 2.8.4
        MONITOR = "MONITOR",
        REMOVE = "REMOVE",
        // SET = "SET",

        // replication states
        connect = "connect",
        connected = "connected",
        connecting = "connecting",
        handshake = "handshake",
        none = "none",
        sync = "sync",

        MinusSymbol = "-",
        PlusSymbol = "+",
        Wildcard = "*",
        ExactTrim = "=",
        ApproxTrim = "~",

        // Stream literals
        StreamAutoGenerateId = "*",
        StreamUndeliveredMessages = ">",
        StreamNewMessages = "$",
        StreamAllMessages = "0",
        StreamMinimumId = "0-0",
        StreamMinId = "-",
        StreamMaxId = "+",
        StreamExactTrim = "=",
        StreamApproxTrim = "~",

        // Sorted set ranges
        RangeInclusive = "[",
        RangeExclusive = "(",
        LexRangeMin = "-",
        LexRangeMax = "+",
        ScoreRangeMin = "-inf",
        ScoreRangeMax = "+inf",
        RankRangeMin = "0",
        RankRangeMax = "-1",

        // Geo Radius/Search Literals
        BYBOX = "BYBOX",
        BYRADIUS = "BYRADIUS",
        FROMMEMBER = "FROMMEMBER",
        FROMLONLAT = "FROMLONLAT",
        STOREDIST = "STOREDIST",
        WITHCOORD = "WITHCOORD",
        WITHDIST = "WITHDIST",
        WITHHASH = "WITHHASH",

        // geo units
        ft = "ft",
        km = "km",
        m = "m",
        mi = "mi",

        // Vector Search (FT.*) command literals
        ALLSHARDS = "ALLSHARDS",
        COSINE = "COSINE",
        DIM = "DIM",
        DISTANCE_METRIC = "DISTANCE_METRIC",
        EF_CONSTRUCTION = "EF_CONSTRUCTION",
        EF_RUNTIME = "EF_RUNTIME",
        FLAT = "FLAT",
        FLOAT32 = "FLOAT32",
        HASH = "HASH",
        HNSW = "HNSW",
        INITIAL_CAP = "INITIAL_CAP",
        IP = "IP",
        APPLY = "APPLY",
        AS = "AS",
        CASESENSITIVE = "CASESENSITIVE",
        CONSISTENT = "CONSISTENT",
        DIALECT = "DIALECT",
        FILTER = "FILTER",
        GROUPBY = "GROUPBY",
        INCONSISTENT = "INCONSISTENT",
        INORDER = "INORDER",
        JSON = "JSON",
        L2 = "L2",
        LANGUAGE = "LANGUAGE",
        LOCAL = "LOCAL",
        M = "M",
        MINSTEMSIZE = "MINSTEMSIZE",
        NOCONTENT = "NOCONTENT",
        NOOFFSETS = "NOOFFSETS",
        NOSTEM = "NOSTEM",
        NOSTOPWORDS = "NOSTOPWORDS",
        NOSUFFIXTRIE = "NOSUFFIXTRIE",
        NUMERIC = "NUMERIC",
        ON = "ON",
        PARAMS = "PARAMS",
        PREFIX = "PREFIX",
        PUNCTUATION = "PUNCTUATION",
        REDUCE = "REDUCE",
        RETURN = "RETURN",
        SCHEMA = "SCHEMA",
        SCORE = "SCORE",
        SEPARATOR = "SEPARATOR",
        SKIPINITIALSCAN = "SKIPINITIALSCAN",
        SLOP = "SLOP",
        SOMESHARDS = "SOMESHARDS",
        SORTABLE = "SORTABLE",
        SORTBY = "SORTBY",
        STAR = "*",
        STOPWORDS = "STOPWORDS",
        TAG = "TAG",
        TEXT = "TEXT",
        VECTOR = "VECTOR",
        TIMEOUT = "TIMEOUT",
        VERBATIM = "VERBATIM",
        WEIGHT = "WEIGHT",
        WITHOFFSETS = "WITHOFFSETS",
        WITHSORTKEYS = "WITHSORTKEYS",
        WITHSUFFIXTRIE = "WITHSUFFIXTRIE",

        // misc (config, etc)
        databases = "databases",
        master = "master",
        no = "no",
        normal = "normal",
        pubsub = "pubsub",
        replica = "replica",
        replica_read_only = "replica-read-only",
        replication = "replication",
        sentinel = "sentinel",
        server = "server",
        slave = "slave",
        slave_read_only = "slave-read-only",
        timeout = "timeout",
        yes = "yes";

    internal static ValkeyValue Get(Bitwise operation) => operation switch
    {
        Bitwise.And => AND,
        Bitwise.Or => OR,
        Bitwise.Xor => XOR,
        Bitwise.Not => NOT,
        _ => throw new ArgumentOutOfRangeException(nameof(operation)),
    };
}
#pragma warning restore SA1310 // Field names should not contain underscore
#pragma warning restore SA1311 // Static readonly fields should begin with upper-case letter

