name: check-links

on:
    push:
        branches:
            - main
            - release-*
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    check-links:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  # Allow validation of links to files in the valkey-glide submodule.
                  submodules: true

            - name: Check links
              uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
              with:
                  args: --config dev/conf/lychee.toml .
                  fail: true
