name: check-examples

on:
    push:
        branches:
            - main
            - release-*
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    check-examples:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  submodules: true

            - name: Setup .NET
              uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
              with:
                  dotnet-version: "8.0.x"

            - name: Setup Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: "3.12"

            - name: Install Task
              run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

            - name: Build Valkey.Glide
              run: task build target=lib

            - name: Check examples
              run: task check-examples
