name: CI

on:
    push:
        branches: [main, release-*, v*]
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    tests:
        uses: ./.github/workflows/test.yml
        with:
            profile: standard
        secrets: inherit
